%YAML:1.0
D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 0.092890, -0.046208, 0.000622, -0.001104, 0.000000]
K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [934.35,   0., 959.92,
          0., 931.2, 552.3,
          0.,   0.     ,   1.    ]
H: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -0.5,-1.5, 358, 512,
         0.5,-1.5, 835, 503,
         0.5,-2.5, 743, 378,
         -0.5,-2.5, 472, 383]
